# Production environment values
replicaCount: 5

image:
  tag: "v1.0.0"  # Use specific version tags in production

ingress:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "500"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: git2in-prod-tls
      hosts:
        - git.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

persistence:
  storageClass: "fast-ssd"
  size: 100Gi

config:
  env: production
  workers: 8
  
  rateLimit:
    requests: 500
    window: 60

backup:
  schedule: "0 1 * * *"  # Daily at 1 AM
  retention: 30  # Keep last 30 backups

monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s

redis:
  enabled: true
  replica:
    replicaCount: 2
  master:
    persistence:
      size: 16Gi

postgresql:
  enabled: true
  architecture: replication
  primary:
    persistence:
      size: 100Gi
  readReplicas:
    replicaCount: 2

priorityClassName: "high-priority"