# Staging environment values
replicaCount: 2

image:
  tag: "staging"

ingress:
  hosts:
    - host: git-staging.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: git2in-staging-tls
      hosts:
        - git-staging.example.com

resources:
  limits:
    cpu: 400m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  size: 20Gi

config:
  env: staging
  logLevel: info

backup:
  schedule: "0 3 * * *"  # Daily at 3 AM
  retention: 5

monitoring:
  serviceMonitor:
    enabled: true