apiVersion: v1
kind: ConfigMap
metadata:
  name: git2in-config
  namespace: git2in
  labels:
    app: git2in
    component: config
data:
  # Application settings
  GIT2IN_ENV: "production"
  GIT2IN_HOST: "0.0.0.0"
  GIT2IN_PORT: "8000"
  GIT2IN_WORKERS: "4"
  
  # Repository configuration
  GIT2IN_REPO_BASE_PATH: "/data/repositories"
  GIT2IN_MAX_REPO_SIZE: "1073741824"  # 1GB in bytes
  GIT2IN_ALLOWED_REPO_EXTENSIONS: ".git"
  
  # Logging configuration
  GIT2IN_LOG_LEVEL: "info"
  GIT2IN_LOG_FORMAT: "json"
  GIT2IN_LOG_DIR: "/data/logs"
  
  # Metrics configuration
  GIT2IN_METRICS_ENABLED: "true"
  GIT2IN_METRICS_PORT: "9090"
  
  # Rate limiting
  GIT2IN_RATE_LIMIT_ENABLED: "true"
  GIT2IN_RATE_LIMIT_REQUESTS: "100"
  GIT2IN_RATE_LIMIT_WINDOW: "60"
  
  # CORS settings
  GIT2IN_CORS_ORIGINS: "*"
  GIT2IN_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  GIT2IN_CORS_HEADERS: "Content-Type,Authorization"
  
  # Feature flags
  GIT2IN_FEATURE_WEBHOOKS: "true"
  GIT2IN_FEATURE_AUDIT_LOG: "true"
  GIT2IN_FEATURE_METRICS: "true"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git2in-config-files
  namespace: git2in
  labels:
    app: git2in
    component: config
data:
  logging.yaml: |
    version: 1
    disable_existing_loggers: false
    
    formatters:
      json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: '%(asctime)s %(name)s %(levelname)s %(message)s'
      
      standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout
      
      file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: json
        filename: /data/logs/git2in.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
    
    root:
      level: INFO
      handlers: [console, file]
    
    loggers:
      git2in:
        level: INFO
        handlers: [console, file]
        propagate: false
      
      uvicorn:
        level: INFO
        handlers: [console]
        propagate: false
      
      uvicorn.access:
        level: WARNING
        handlers: [console]
        propagate: false
  
  git-config.ini: |
    [core]
    bare = true
    sharedRepository = group
    
    [receive]
    denyNonFastForwards = false
    denyDeletes = false
    
    [transfer]
    fsckObjects = true
    
    [uploadpack]
    allowFilter = true
    allowAnySHA1InWant = true
    
    [http]
    receivepack = true
    uploadpack = true