apiVersion: v1
kind: ServiceAccount
metadata:
  name: git2in-api
  namespace: git2in
  labels:
    app: git2in
    component: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git2in-api
  namespace: git2in
  labels:
    app: git2in
    component: api
rules:
# Allow reading configmaps and secrets in the namespace
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow updating configmaps for distributed locking if needed
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
# Allow reading pods for service discovery
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git2in-api
  namespace: git2in
  labels:
    app: git2in
    component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git2in-api
subjects:
- kind: ServiceAccount
  name: git2in-api
  namespace: git2in